# Simulation parameters
simulation:
  verbose: 1            # 0 = None, 1 = run-level, 2 = episode-level, 3 = step-level
  log: false            # Log all output (set to false when testing)
  vizLearning: false    # Visualize Q-value back-propagation?
  bucket: true          # Save to bucket?

# Learning parameters for the Dyna agent
dyna:
  episodes: 1000 # Number of simulation episodes for a simulation run (default: 1000)
  runs: 5000     # Number of simulation runs (default: 5000; runtime at 5000 ~ 14 hours)
  gamma: 0.9     # Discount factor for Q-learning continuation value (default: 0.9)
  rho: 4         # Number of indirect planning steps per agent per episode (default: 4)
  epsilon: 0.1   # Probability of taking a random action on each step (default: 0.1)
  alpha: 0.3     # Learning rate for Q-Learning when ùù∫ = 1 (default: 0.3)
  nu: 0.35       # Scaling of learning rate (ùõÇ) as a function of specialization (ùù∫) (default: 0.35)
  lambda: 2      # Number of agents in a simulation (1, 2 or 4)
  tau: 0         # Share of episodes that are automated in a simulation
  kappa: 0       # Time-based weight for model learning (default: 0)
  phi: 0.5       # Percentage of coordination costs incurred under automation (ùõï) (default: 0.5)
  psi: 0         # Costs to transition in or out of automation as a function of lambda ( œà * ùù∫ ) (default: 0)

# Maze parameters
maze:
  stepCost: 1        # Cost to make a step
  stepsLongPath: 11  # Steps required for the risk-free path
  stepsShortPath: 7  # Steps required for the risky path
  delta: 0           # Number of times environment changes in a simulation
  eta: 0.9           # Scaling of coordination costs as a function of specialization (ùù∫) (default: 0.9)
  pi: 10             # Scaling of reward at goal state as a function of specialization (ùù∫) (default: 10)
  initDoor: half     # "closed" or "random" or "half" (default: half)
  doorSwitching: intervals  # "random" or "intervals" (default: intervals)
  startState: [6, 6]
  conditionalBanditStates:
    - [3, 6]
    - [9, 6]
    - [6, 3]
    - [6, 9]
  doorStates:
    - [2, 4]  # Domain 1
    - [10, 8] # Domain 2
    - [8, 2]  # Domain 3
    - [4, 10] # Domain 4
  goalStates:
    - [1, 4]  # Domain 1
    - [11, 8] # Domain 2
    - [8, 1]  # Domain 3
    - [4, 11] # Domain 4
  wallStates:
    - [ 0, 0 ]
    - [ 0, 1 ]
    - [ 0, 2 ]
    - [ 0, 3 ]
    - [ 0, 4 ]
    - [ 0, 5 ]
    - [ 0, 6 ]
    - [ 0, 7 ]
    - [ 0, 8 ]
    - [ 0, 9 ]
    - [ 0, 10 ]
    - [ 0, 11 ]
    - [ 0, 12 ]
    - [ 1, 0 ]
    - [ 1, 1 ]
    - [ 1, 2 ]
    - [ 1, 3 ]
    - [ 1, 9 ]
    - [ 1, 10 ]
    - [ 1, 11 ]
    - [ 1, 12 ]
    - [ 2, 0 ]
    - [ 2, 1 ]
    - [ 2, 2 ]
    - [ 2, 3 ]
    - [ 2, 5 ]
    - [ 2, 6 ]
    - [ 2, 7 ]
    - [ 2, 9 ]
    - [ 2, 10 ]
    - [ 2, 11 ]
    - [ 2, 12 ]
    - [ 3, 0 ]
    - [ 3, 1 ]
    - [ 3, 2 ]
    - [ 3, 3 ]
    - [ 3, 9 ]
    - [ 3, 10 ]
    - [ 3, 11 ]
    - [ 3, 12 ]
    - [ 4, 0 ]
    - [ 4, 4 ]
    - [ 4, 5 ]
    - [ 4, 7 ]
    - [ 4, 8 ]
    - [ 4, 12 ]
    - [ 5, 0 ]
    - [ 5, 2 ]
    - [ 5, 4 ]
    - [ 5, 5 ]
    - [ 5, 7 ]
    - [ 5, 8 ]
    - [ 5, 10 ]
    - [ 5, 12 ]
    - [ 6, 0 ]
    - [ 6, 2 ]
    - [ 6, 10 ]
    - [ 6, 12 ]
    - [ 7, 0 ]
    - [ 7, 2 ]
    - [ 7, 4 ]
    - [ 7, 5 ]
    - [ 7, 7 ]
    - [ 7, 8 ]
    - [ 7, 10 ]
    - [ 7, 12 ]
    - [ 8, 0 ]
    - [ 8, 4 ]
    - [ 8, 5 ]
    - [ 8, 7 ]
    - [ 8, 8 ]
    - [ 8, 12 ]
    - [ 9, 0 ]
    - [ 9, 1 ]
    - [ 9, 2 ]
    - [ 9, 3 ]
    - [ 9, 9 ]
    - [ 9, 10 ]
    - [ 9, 11 ]
    - [ 9, 12 ]
    - [ 10, 0 ]
    - [ 10, 1 ]
    - [ 10, 2 ]
    - [ 10, 3 ]
    - [ 10, 5 ]
    - [ 10, 6 ]
    - [ 10, 7 ]
    - [ 10, 9 ]
    - [ 10, 10 ]
    - [ 10, 11 ]
    - [ 10, 12 ]
    - [ 11, 0 ]
    - [ 11, 1 ]
    - [ 11, 2 ]
    - [ 11, 3 ]
    - [ 11, 9 ]
    - [ 11, 10 ]
    - [ 11, 11 ]
    - [ 11, 12 ]
    - [ 12, 0 ]
    - [ 12, 1 ]
    - [ 12, 2 ]
    - [ 12, 3 ]
    - [ 12, 4 ]
    - [ 12, 5 ]
    - [ 12, 6 ]
    - [ 12, 7 ]
    - [ 12, 8 ]
    - [ 12, 9 ]
    - [ 12, 10 ]
    - [ 12, 11 ]
    - [ 12, 12 ]
  shortpathStates:
    - [3, 5] # Domain 1
    - [3, 4]
    - [2, 4]
    - [9, 7] # Domain 2
    - [9, 8]
    - [10, 8]
    - [7, 3] # Domain 3
    - [8, 3]
    - [8, 2]
    - [5, 9] # Domain 4
    - [4, 9]
    - [4, 10]
  neutralStates:
    - [6, 6] # Start
    - [5, 6] # Domain 1
    - [4, 6]
    - [3, 6]
    - [7, 6] # Domain 2
    - [8, 6]
    - [9, 6]
    - [6, 5] # Domain 3
    - [6, 4]
    - [6, 3]
    - [6, 7] # Domain 4
    - [6, 8]
    - [6, 9]

